- name: Check if logrotate package is already installed
  shell: "[[ `dpkg -s logrotate | grep 'Status'` =~ installed ]]"
  register: logrotate_pkg_presence_test_command
  ignore_errors: true
  no_log: true

- set_fact:
    logrotate_pkg_presence: "{{ logrotate_pkg_presence_test_command.rc == 0 }}"

- name: Retrieve anacron dirs
  shell: 'ls /etc/cron.*ly -d'
  register: anacron_directories_test_command
  ignore_errors: true
  no_log: true

- set_fact:
    anacron_directories: "{{ anacron_directories_test_command.stdout_lines }}"
  when: "{{ anacron_directories_test_command.rc == 0 }}"

- set_fact:
    anacron_directories: "[]"
  when: "{{ anacron_directories_test_command.rc != 0 }}"

- name: Manage logrotate file for given anacron directory
  include: manage_logrotate_files_in_anacron_directory.yml
  with_items: "{{ anacron_directories }}"
  loop_control:
    loop_var: anacron_directory
